### ISSUE TITLE
Newcases and Newdeaths are not available anymore

### ISSUE THREAD

**Issue by thebino** [thebino/rki-covid-parser#21]
**🐛 Describe the bug**

Multiple values like `newCases` and `newDeaths` are not available anymore

**💥 When did the bug occurred.***

Always

**💻 Versions (please complete the following information):**

 - Python: 3.9.10
 - RKI-Covid-Parser: 1.3.1
 - OS: independent

**🗄 Stacktrace**

> 🎓 Please try to add as many data to reproduce the issue.

**Comment by thebino** [comment]
Solved with the latest release [version 1.3.2](https://github.com/thebino/rki-covid-parser/releases/tag/v1.3.2)

**Comment by swanitzek** [comment]
When will the fixed version be available via HACS?

**Comment by thebino** [comment]
@swanitzek it is now available with the latest version 1.5.8

**Comment by swanitzek** [comment]
Perfect! It works again. Thank you very much.

**Comment by Kepana808** [comment]
Thanks a lot, I got my numbers back 👍
